### ISSUE TITLE
Apache avro crash in clion

### ISSUE THREAD

**Issue by LennyThompson** [opwvhk/avro-schema-support#79]
Crash Report
What happened
(The user did not submit additional information)

Context information
Plugin: Apache Avro IDL Schema Support 213.4.2 by Oscar Westra van Holthe - Kind (id: net.sf.opk.avro-schema-support)
IDE: CLion 2022.3.2
JVM: OpenJDK 64-Bit Server VM (JetBrains s.r.o.) 17.0.5+1-b653.25
OS: Windows 10 (amd64) 10.0
Exception
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at opwvhk.intellij.avro_idl.actions.AvroIdlNotifications.showNotification(AvroIdlNotifications.java:22)
	at opwvhk.intellij.avro_idl.AvroIdlPluginUpdateStartupActivity.notifyUserOfUpdate(AvroIdlPluginUpdateStartupActivity.java:95)
	at opwvhk.intellij.avro_idl.AvroIdlPluginUpdateStartupActivity.runActivity(AvroIdlPluginUpdateStartupActivity.java:53)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:340)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$Companion$addActivityEpListener$1$extensionAdded$1.invokeSuspend(StartupManagerImpl.kt:86)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by opwvhk** [comment]
Odd: this means the notification group (defined in `plugin.xml`) cannot be found...

**Comment by opwvhk** [comment]
Cannot reproduce. Seems to be caused by the same / a similar cause as #63, which I haven't been able to reproduce either.
