### ISSUE TITLE
Crash Report: jar file cannot be null, path = /snap/intellij-idea-ultimate/437/plugins/javascript-impl/lib/javascript-impl.jar

### ISSUE THREAD

**Issue by opwvhk** [opwvhk/avro-schema-support#99]
# Crash Report

## What happened

(The user did not submit additional information)

## Context information

* Plugin:  Apache Avro IDL Schema Support `213.5.2` by Oscar Westra van Holthe - Kind (id: net.sf.opk.avro-schema-support)
* IDE: IntelliJ IDEA `2023.1.3`
* JVM: OpenJDK 64-Bit Server VM (JetBrains s.r.o.) `17.0.7+10-b829.16`
* OS: Linux (amd64) `6.3.0-1-amd64`

## Exception

```
java.lang.RuntimeException: jar file cannot be null, path = /snap/intellij-idea-ultimate/437/plugins/javascript-impl/lib/javascript-impl.jar
	at com.intellij.lang.javascript.ecmascript6.TypeScriptUtil.getTypeScriptCompilerFolderFile(TypeScriptUtil.java:823)
	at com.intellij.lang.javascript.library.JSCorePredefinedLibrariesProvider.getAndCacheFromCompilerFolder(JSCorePredefinedLibrariesProvider.java:268)
	at com.intellij.lang.javascript.library.JSCorePredefinedLibrariesProvider.getLibFiles(JSCorePredefinedLibrariesProvider.java:254)
	at com.intellij.lang.javascript.library.JSCorePredefinedLibrariesProvider.getRequiredLibraryFilesForResolve(JSCorePredefinedLibrariesProvider.java:193)
	at com.intellij.lang.javascript.library.JSPredefinedLibrariesData.create(JSPredefinedLibrariesData.java:114)
	at com.intellij.lang.javascript.library.JSPredefinedLibraryManager.lambda$new$0(JSPredefinedLibraryManager.java:25)
	at com.intellij.openapi.util.ClearableLazyValue$2.compute(ClearableLazyValue.java:26)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:44)
	at com.intellij.openapi.util.AtomicClearableLazyValue.getValue(AtomicClearableLazyValue.java:9)
	at com.intellij.lang.javascript.library.JSPredefinedLibraryManager.getLibraryFiles(JSPredefinedLibraryManager.java:39)
	at com.intellij.lang.javascript.index.JSIndexedRootProvider.getPredefinedLibraryFiles(JSIndexedRootProvider.java:29)
	at com.intellij.webcore.libraries.ScriptingIndexableSetContributor.getAdditionalProjectRootsToIndex(ScriptingIndexableSetContributor.java:20)
	at com.intellij.util.indexing.IndexableSetContributor.getProjectRootsToIndex(IndexableSetContributor.java:33)
	at com.intellij.util.indexing.AdditionalIndexableFileSet.collectFilesAndDirectories(AdditionalIndexableFileSet.java:54)
	at com.intellij.util.indexing.AdditionalIndexableFileSet.lambda$new$3(AdditionalIndexableFileSet.java:35)
	at com.intellij.util.CachedValueImpl.doCompute(CachedValueImpl.java:22)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:244)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:244)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.util.CachedValueImpl.getValue(CachedValueImpl.java:33)
	at com.intellij.util.indexing.AdditionalIndexableFileSet.isInSet(AdditionalIndexableFileSet.java:70)
	at com.intellij.util.indexing.FileBasedIndexImpl$6.isInSet(FileBasedIndexImpl.java:289)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingProjects(FileBasedIndexImpl.java:1850)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$ensureFileBelongsToIndexableFilter$32(FileBasedIndexImpl.java:2004)
	at com.intellij.util.indexing.projectFilter.IncrementalProjectIndexableFilesFilterHolder$addFileId$matchedProjects$2.invoke(ProjectIndexableFilesFilterHolder.kt:80)
	at com.intellij.util.indexing.projectFilter.IncrementalProjectIndexableFilesFilterHolder$addFileId$matchedProjects$2.invoke(ProjectIndexableFilesFilterHolder.kt:80)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at com.intellij.util.indexing.projectFilter.IncrementalProjectIndexableFilesFilterHolder.addFileId$lambda$1(ProjectIndexableFilesFilterHolder.kt:80)
	at com.intellij.util.indexing.projectFilter.IncrementalProjectIndexableFilesFilterHolder.access$addFileId$lambda$1(ProjectIndexableFilesFilterHolder.kt:45)
	at com.intellij.util.indexing.projectFilter.IncrementalProjectIndexableFilesFilterHolder$addFileId$statuses$1$1.invoke(ProjectIndexableFilesFilterHolder.kt:83)
	at com.intellij.util.indexing.projectFilter.IncrementalProjectIndexableFilesFilterHolder$addFileId$statuses$1$1.invoke(ProjectIndexableFilesFilterHolder.kt:82)
	at com.intellij.util.indexing.projectFilter.IncrementalProjectIndexableFilesFilter.ensureFileIdPresent(IncrementalProjectIndexableFilesFilter.kt:25)
	at com.intellij.util.indexing.projectFilter.IncrementalProjectIndexableFilesFilterHolder.addFileId(ProjectIndexableFilesFilterHolder.kt:82)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureFileBelongsToIndexableFilter(FileBasedIndexImpl.java:2004)
	at com.intellij.util.indexing.FileBasedIndexImpl.scheduleFileForIndexing(FileBasedIndexImpl.java:1929)
	at com.intellij.util.indexing.events.ChangedFilesCollector$4.process(ChangedFilesCollector.java:232)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.lambda$process$0(ChangedFilesCollector.java:271)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.lambda$process$1(ChangedFilesCollector.java:270)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:248)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.process(ChangedFilesCollector.java:268)
	at com.intellij.util.indexing.events.VfsEventsMerger.processChanges(VfsEventsMerger.java:99)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesInReadAction(ChangedFilesCollector.java:265)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesToUpdateInReadAction(ChangedFilesCollector.java:224)
	at com.intellij.util.indexing.events.ChangedFilesCollector.ensureUpToDate(ChangedFilesCollector.java:190)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:836)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:316)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(FileBasedIndexEx.java:434)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(FileBasedIndexEx.java:392)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:1194)
	at com.intellij.util.indexing.FileBasedIndexEx.processValues(FileBasedIndexEx.java:295)
	at com.intellij.util.indexing.FileBasedIndexEx.processValues(FileBasedIndexEx.java:283)
	at org.jetbrains.kotlin.idea.base.indices.KotlinPackageIndexUtils.packageExists(KotlinPackageIndexUtils.kt:38)
	at org.jetbrains.kotlin.idea.caches.resolve.IDEKotlinAsJavaSupport.packageExists(IDEKotlinAsJavaSupport.kt:85)
	at org.jetbrains.kotlin.asJava.finder.JavaElementFinder.findPackage(JavaElementFinder.kt:127)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findPackage(JavaPsiFacadeImpl.java:202)
	at de.plushnikov.intellij.plugin.util.LombokLibraryUtil.lambda$hasLombokLibrary$0(LombokLibraryUtil.java:34)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:244)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:244)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at de.plushnikov.intellij.plugin.util.LombokLibraryUtil.hasLombokLibrary(LombokLibraryUtil.java:33)
	at de.plushnikov.intellij.plugin.extension.LombokHighlightErrorFilter.accept(LombokHighlightErrorFilter.java:67)
	at com.intellij.codeInsight.daemon.impl.HighlightInfoB.isAcceptedByFilters(HighlightInfoB.java:302)
	at com.intellij.codeInsight.daemon.impl.HighlightInfoB.create(HighlightInfoB.java:273)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.createHighlightsForDescriptor(LocalInspectionsPass.java:312)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.addDescriptorIncrementally(LocalInspectionsPass.java:206)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$collectInformationWithProgress$2(LocalInspectionsPass.java:109)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner$InspectionProblemHolder.registerProblem(InspectionRunner.java:441)
	at com.intellij.codeInspection.ProblemsHolder.registerProblem(ProblemsHolder.java:52)
	at com.intellij.codeInspection.ProblemsHolder.registerProblem(ProblemsHolder.java:45)
	at opwvhk.intellij.avro_idl.inspections.AvroIdlUseNullableShorthandInspection.visitElement(AvroIdlUseNullableShorthandInspection.java:27)
	at opwvhk.intellij.avro_idl.inspections.AvroIdlUseNullableShorthandInspection.visitElement(AvroIdlUseNullableShorthandInspection.java:17)
	at opwvhk.intellij.avro_idl.inspections.BaseAvroIdlInspection$1.visitElement(BaseAvroIdlInspection.java:29)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at opwvhk.intellij.avro_idl.psi.impl.AvroIdlWithSchemaPropertiesImpl.accept(AvroIdlWithSchemaPropertiesImpl.java:27)
	at opwvhk.intellij.avro_idl.psi.impl.AvroIdlTypeImpl.accept(AvroIdlTypeImpl.java:27)
	at opwvhk.intellij.avro_idl.psi.impl.AvroIdlUnionTypeImpl.accept(AvroIdlUnionTypeImpl.java:27)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:323)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:331)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:337)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:300)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:300)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:299)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:284)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:272)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:436)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:670)
	at com.intellij.concurrency.JobLauncherImpl.processQueue(JobLauncherImpl.java:360)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processInOrder(InspectionRunner.java:299)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.visitElements(InspectionRunner.java:274)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$4(InspectionRunner.java:129)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:227)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:114)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:115)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:373)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:349)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:347)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.RuntimeException: jar file cannot be null, path = /snap/intellij-idea-ultimate/437/plugins/javascript-impl/lib/javascript-impl.jar
	at com.intellij.lang.javascript.ecmascript6.TypeScriptUtil.getTypeScriptCompilerFolderFile(TypeScriptUtil.java:817)
	... 146 more
```

**Comment by opwvhk** [comment]
The issue hasn't occurred for a long while. It seems JetBrains fixed the issue.
